name: Build, Test, and Publish Image to ECR

on: 
  push:
    branches: [ dev ]
  workflow_dispatch:  # Enables manual trigger

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build MySQL Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mysql_repo
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:v${IMAGE_TAG}" -f Dockerfile_mysql .
        docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:v${IMAGE_TAG}"

    - name: Build WebApp Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: webapp_repo
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:v${IMAGE_TAG}" -f Dockerfile .
        docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:v${IMAGE_TAG}"

    - name: Test MySQL (Optional step)
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mysql_repo
        IMAGE_TAG: ${{ github.run_number }}
        DBPASS: pw
        DBUSER: ${{ secrets.DBUSER }}
      run: |
        docker network create my_app_network || true
        docker run -d --name my_db --network my_app_network -e MYSQL_ROOT_PASSWORD=$DBPASS "${ECR_REGISTRY}/${ECR_REPOSITORY}:v${IMAGE_TAG}"
        until docker exec my_db mysqladmin -u root -p$DBPASS ping --silent; do
          echo "Waiting for MySQL connection..."
          sleep 30
        done

    - name: Test WebApp (Optional step)
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: webapp_repo
        IMAGE_TAG: ${{ github.run_number }}
        DBPASS: ${{ secrets.DBPASS }}
        DBUSER: ${{ secrets.DBUSER }}
      run: |
        export DBHOST=$(docker inspect -f '{{.NetworkSettings.Networks.my_app_network.IPAddress}}' my_db)
        export DBPORT=3306
        export DBUSER=$DBUSER
        export DATABASE=employees
        export DBPWD=$DBPASS

        docker run -d --name app_blue -p 8081:8080 -e DBHOST=$DBHOST -e DBPORT=$DBPORT -e DBUSER=$DBUSER -e DBPWD=$DBPASS -e APP_COLOR="blue" "${ECR_REGISTRY}/${ECR_REPOSITORY}:v${IMAGE_TAG}"
        docker run -d --name app_pink -p 8082:8080 -e DBHOST=$DBHOST -e DBPORT=$DBPORT -e DBUSER=$DBUSER -e DBPWD=$DBPASS -e APP_COLOR="pink" "${ECR_REGISTRY}/${ECR_REPOSITORY}:v${IMAGE_TAG}"
        docker run -d --name app_lime -p 8083:8080 -e DBHOST=$DBHOST -e DBPORT=$DBPORT -e DBUSER=$DBUSER -e DBPWD=$DBPASS -e APP_COLOR="lime" "${ECR_REGISTRY}/${ECR_REPOSITORY}:v${IMAGE_TAG}"
        sleep 15
        docker ps
        curl -I localhost:8081
        curl -I localhost:8082
        curl -I localhost:8083

    - name: Create Pull Request to Prod
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        gh pr create -B prod -H dev --title 'Merge dev into prod' --body 'Update changes - by Github action'

